### ISSUE TITLE
Send Formatted Stack Traces

### ISSUE THREAD

**Issue by Crisfole** [elixir-addicts/rollbax#14]
Right now this package only sends string messages. You lose out on lots of good stuff like grouping, linking to source files, and tons of other goodies by underusing the API!

The docs are here: https://rollbar.com/docs/api/items_post/

What you're looking for is the child of `body`. Right now you send `{ message: { body: "STRINGIFIED EXCEPTION" } }`. What you ought to be sending is the `trace` or `trace_chain`.

**Comment by whatyouhide** [comment]
Fixed in #19.
