### ISSUE TITLE
* (ArgumentError) the configuration parameter :access_token is not set

### ISSUE THREAD

**Issue by mikebaldry** [elixir-addicts/rollbax#27]
even if `enabled` is `false` or `:log`, same for `environment`

**Comment by lexmag** [comment]
I think it's the same as #9.

**Comment by whatyouhide** [comment]
Good point, but we can maybe find a better solution, like warning? I'm not sure.

**Comment by mikebaldry** [comment]
Ah yes, my bad. Will comment there.

**Comment by mikebaldry** [comment]
Never mind is closed.. I think newcomers are able to see the parameters required from the documentation. I'd get kind of annoyed if every time I started my app in development, it warned me that my app wasn't setup ready for production (I know, its not, I'm running in development mode!)

**Comment by whatyouhide** [comment]
So, it makes sense not to issue a warning but then it makes sense to blow up with an error everytime if it's not set (plus the implementation is very easy this way, raising when there's no `:access_token`). Let's close this with the same discussion as #9.
