### ISSUE TITLE
Prune invalid UTF-8

### ISSUE THREAD

**Issue by ericmj** [elixir-addicts/rollbax#33]
If anyone logs invalid chardata rollbax will currently crash. I suggest adding this function https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/formatter.ex#L49-L66 until this library can depend on Elixir v1.3.

**Comment by ericmj** [comment]
The reason is because this line of code https://github.com/elixir-addicts/rollbax/blob/1cad341d6597b6e11e89ac103b5ea40a5ed19074/lib/rollbax/logger.ex#L95 can crash with the error `(UnicodeConversionError) invalid encoding starting at <<133>>`.

**Comment by whatyouhide** [comment]
@ericmj I'll release 0.6.1 later with this bug fixed, thanks for the great catch and report!
