### ISSUE TITLE
Reporting error in async tasks with Plug and Phoenix

### ISSUE THREAD

**Issue by hopsor** [elixir-addicts/rollbax#36]
Hi guys,

We are using Rollbax in a Phoenix Framework project. It's helping us a lot tracking errors to rollbar but we have realized one thing we are not really sure how to solve. When we have an error as a result of executing a function inside `Task.start` the error isn't being handled by the `handle_errors` private function we declared in `router.ex` which prevent us from reporting it. 

I guess this happens because that code is executed by a different process or something.

Do you guys know any way to handle these errors?

Thank you.

**Comment by jaimeiniesta** [comment]
Hey @hopsor, to notify errors happening in background processes you need to monitor the logs, as [explained here](https://github.com/elixir-addicts/rollbax#logger-backend).

This is how I do it:

```elixir
# Logs will be sent to console and Rollbax Logger
config :logger,
  backends: [:console, Rollbax.Logger]

# Configures Elixir's Logger
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id]

# Configures the Rollbax.Logger backend.
config :logger, Rollbax.Logger,
  level: :error
```

**Comment by whatyouhide** [comment]
Yep, you either call `Rollbax.report/3-5` explicitly (e.g., in your error handler) or you setup the `Rollbax.Logger` Logger backend to log stuff that is logged with the `:error` level (which includes crash reports). :)

**Comment by hopsor** [comment]
That's really helpful. Thanks for the quick response @jaimeiniesta @whatyouhide !
