### ISSUE TITLE
What is reason to use `hackney` directly instead of use `httpoison` library?

### ISSUE THREAD

**Issue by kiennt** [elixir-addicts/rollbax#37]
I am new to elixir. I am sorry if my question is trivial

I wonder what is the benefit of using `hackney` directly instead of use `httpoison`?

**Comment by whatyouhide** [comment]
First of all, HTTPoison is built on top of hackney (which is thus a dependency of HTTPoison). The reasons we didn't go with HTTPoison are:

* hackney introduces one less level of dependency (e.g., what if hackney updates but HTTPoison doesn't update that); this is especially important given this is a library other projects/people will depend on, so introducing one less dependency for them is important (and as far as I'm concerned, this is the main reason)
* HTTPoison is a bit less tweakable than hackney in favour of an easier interface
