### ISSUE TITLE
Should I need to specify an access_token for `enabled: :log` ?

### ISSUE THREAD

**Issue by Lugghawk** [elixir-addicts/rollbax#38]
I've created a trial Rollbar account and installed Rollbax into my application. But for development purposes I've specified `enabled: :log` in my config/dev.exs so that I'm not spamming my limited rollbar account while I'm adding logging procedures around my code.

However during startup it tells me to add an access token, which I don't feel is necessary because it won't be sending anything to rollbar yet.

Additionally, I'd like to keep my access_token in `prod.secret.exs` instead of anything I commit to my public repo, but would like the development environment to pretty much work out of the box.

**Comment by whatyouhide** [comment]
@Lugghawk hey there, thanks for opening the issue!

I think you should be able to use a bogus token alongside `enabled: :log`, as if no requests are actually sent to Rollbar then the access token is never used. So you would have something like this in `config/config.exs` (or `dev.exs` or whatever you want to put this non-production configuration):

```elixir
config :rollbax,
  enabled: :log,
  access_token: ""
```

and then something like this in `prod.secret.exs`:

```elixir
config :rollbax,
  enabled: true,
  access_token: "your real access token"
```

Can you try something like this out and let me know if it works? :)

**Comment by Lugghawk** [comment]
That worked, thanks.

**Comment by whatyouhide** [comment]
No worries, glad to help :)
