### ISSUE TITLE
"no function clause matching" error in rollbax 0.6.1

### ISSUE THREAD

**Issue by SimonWoolf** [elixir-addicts/rollbax#44]
Just upgraded to rollbax 0.6.1 from 0.5, and have started to see some errors:
```
15:19:53.821 [error]  GenServer Rollbax.Client terminating
** (FunctionClauseError) no function clause matching in Rollbax.Client.handle_hackney_response/3
    (rollbax) lib/rollbax/client.ex:100: Rollbax.Client.handle_hackney_response(#Reference<0.0.1.7727>, {:status, 200, "OK"}, %{__struct__: Rollbax.Client, draft: %{"access_token" => "<redacted>", "data" => %{"environment" => "dev", "language" => "Elixir v1.2.5", "notifier" => %{"name" => "Rollbax", "version" => "0.6.1"}, "platform" => "Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]", "server" => %{"host" => "6d6fbf0e20d7"}}}, enabled: true, url: "https://api.rollbar.com/api/1/item/"})
    (rollbax) lib/rollbax/client.ex:79: Rollbax.Client.handle_info/2
    (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:681: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:hackney_response, #Reference<0.0.1.7727>, {:status, 200, "OK"}}
State: %{__struct__: Rollbax.Client, draft: %{"access_token" => "<redacted>", "data" => %{"environment" => "dev", "language" => "Elixir v1.2.5", "notifier" => %{"name" => "Rollbax", "version" => "0.6.1"}, "platform" => "Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]", "server" => %{"host" => "6d6fbf0e20d7"}}}, enabled: true, url: "https://api.rollbar.com/api/1/item/"}
```

**Comment by whatyouhide** [comment]
Hey @SimonWoolf, did you restart your application or did you do some kind of hot reload? The state of `Rollbax.Client` there has no `:hackney_responses` field which is present in version >= 0.6.0.

**Comment by SimonWoolf** [comment]
Hi! Thanks for the quick response :)

Nope, we're not using hot code reloading, new versions are run in their own fresh docker containers. I can see why you'd ask that though -- looking at client.ex I can't see any obvious way for a client to end up without a `:hackney_responses` field.  But in any case, the client was restarted by the supervisor and died multiple times with the same error (until the supervisor gave up); if it was a hot code reloading thing, that would only have affected the first one.

Very odd :/

**Comment by whatyouhide** [comment]
Yes, that's quite weird :| Do you have anything I could use to reproduce this?

**Comment by SimonWoolf** [comment]
After upgrading to the latest version of the elixir buildpack and wiping the slugbuilder cache, I can no longer reproduce this. I still have no idea wtf was happening, but whatever it was, I'm now pretty sure it wasn't a bug in rollbax. Apologies for the noise, and thanks :)

**Comment by whatyouhide** [comment]
Awesome, no worries @SimonWoolf :D 👍
