### ISSUE TITLE
Docs mismatch

### ISSUE THREAD

**Issue by noma4i** [elixir-addicts/rollbax#47]
Correct doc: Using Rollbax in Plug-based applications.md
Outdated doc: https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html

Outdated doc has typo around stacktrace variable.

**Comment by whatyouhide** [comment]
I'm lost, I have no idea what this bug report means, sorry :(

**Comment by noma4i** [comment]
Scope of this issue is:
 Doc page at hexdocs has typo/error while corresponding markdown file in repo is correct.
Solutions:
push docs to hexdocs.pm again to update em. ;)

**Comment by whatyouhide** [comment]
I pushed the docs again but it would be useful to know where this typo is, it's not very helpful to know there's a typo in there :)

**Comment by noma4i** [comment]
Hexdocs:
```
Rollbax.report(kind, reason, stack, %{}, conn_data)
```

This repo md file:
```
Rollbax.report(kind, reason, stacktrace, %{}, conn_data)
```

**Comment by noma4i** [comment]
I see Hexdocs been updated ;)

**Comment by whatyouhide** [comment]
Oh, okay. Glad it was fixed, thanks for the report :)
