### ISSUE TITLE
How to prevent running on dev server?

### ISSUE THREAD

**Issue by simonh1000** [elixir-addicts/rollbax#52]
I'm finding that my dev server is also reporting errors to rollbar, which is confusing for other devs. How do I configure to prevent this?

I have this is config.exs
```
config :rollbax,
  access_token: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  environment: "production"
```

and `IO.inspect(Mix.env)` returns `:dev`

**Comment by whatyouhide** [comment]
Hey @simonh1000, what do you mean by "dev server"? In what Mix environment is this "dev server" running? What's the Rollbax configuration that you're using?

**Comment by simonh1000** [comment]
@whatyouhide Just improved my question

**Comment by whatyouhide** [comment]
Can you try setting the `:enabled`config for `:rollbax` to either `false` or `:log` in the `:dev` environment? If you have a `dev.exs` set it there otherwise you can do something like

```elixir
if Mix.env == :dev do
  config :rollbax, :enabled, false
end
```

(also, I suggest to remove the access token from the issue if that's you actual access token, just to be sure 😃)

**Comment by whatyouhide** [comment]
@simonh1000 heyo, did my suggestion work? If so, can I close this? :)

**Comment by simonh1000** [comment]
yes, this seems to have done the trick
