### ISSUE TITLE
Better error message titles

### ISSUE THREAD

**Issue by isaiahdw** [elixir-addicts/rollbax#56]
Does anyone else have issues with GenSever error message titles?

Almost all our errors result in a GenServer crashing, so the error title is always something like `GenServer #PID<0.934.0> terminating`. This isn't very helpful and I find myself having to click every error we get on rollbar to see what actually happened. Having better titles would be great.

Ideally, I want to see the second line of the message as the error title (see example below). I think we can do this be manually sending the second line as the exception `title`. See: https://rollbar.com/docs/api/items_post/

Example Error

````
GenServer #PID<0.934.0> terminating
** (UndefinedFunctionError) function nil.id/0 is undefined (module nil is not available)
    nil.id()
    (sre) Sre.ListingChannel.handle_in/3
    (phoenix) lib/phoenix/channel/server.ex:226: anonymous fn/4 in Phoenix.Channel.Server.handle_info/2
    (stdlib) gen_server.erl:601: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:667: :gen_server.handle_msg/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
````

**Comment by whatyouhide** [comment]
I am not sure it is that straightforward because these messages are output by Logger and we simply send the whole message to Rollbar. We can't generally take the second line of a logged messages otherwise things like

```elixir
Logger.error("foo\nbar")
```

would not behave as expected. But having `GenServer ... terminating` is indeed not very useful, I agree.

**Comment by BennyHallett** [comment]
I had to work around this earlier this week. There are 2 options:

A lot of these errors are Erlang errors, which as @whatyouhide mentioned, come through via Logger. Logger has the ability to translate these errors along the way: https://hexdocs.pm/logger/Logger.Translator.html . Here's the implementation for the default one if you need ideas on how to translate them: https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger/translator.ex

The other option is to use Rollbar's custom grouping feature: https://rollbar.com/docs/custom-grouping/ . You can match on the text around the process ids to group the errors better. Not an ideal solution but pretty easy to set up.

**Comment by whatyouhide** [comment]
Hey @BennyHallett, lots of work is already happening in #62 to rework logging support. I will close this issue once we finish and merge the PR.

**Comment by Hermanverschooten** [comment]
Are you still working on #62?

**Comment by whatyouhide** [comment]
@Hermanverschooten yes we are, I am actually waiting for feedback from @lexmag :bowtie:

**Comment by whatyouhide** [comment]
Closing since #62 was merged.
