### ISSUE TITLE
Require access token when enabled only

### ISSUE THREAD

**Issue by tt** [elixir-addicts/rollbax#64]
Rollbax requires an access token (and an environment) even when disabled or set to log mode.

I use the following configuration in config/config.exs:

    config :rollbax,
      access_token: {:system, "ROLLBAR_ACCESS_TOKEN"},
      environment: {:system, "ROLLBAR_ENVIRONMENT"}

I then set it to log mode for testing:

    config :rollbax,
      enabled: :log

`mix test` will still fail:

    ** (Mix) Could not start application rollbax: exited in: Rollbax.start(:normal, [])
        ** (EXIT) an exception was raised:
            ** (ArgumentError) system environment variable "ROLLBAR_ACCESS_TOKEN" is not set
                (rollbax) lib/rollbax.ex:136: Rollbax.fetch_and_resolve_config/1
                (rollbax) lib/rollbax.ex:54: Rollbax.start/2
                (kernel) application_master.erl:273: :application_master.start_it_old/4

I know that I can run `mix test --no-start` but other applications do need to start. I'm using Elixir 1.4 and could make it not infer the application by using `{:rollbax, "~> 0.8.1", runtime: Mix.env != :test}`.

All workarounds require more code to use Rollbax, though, so I thought it would be nice to make these required only when they really are.

I'm happy to submit a pull request for this change.

**Comment by whatyouhide** [comment]
I am 👍 for this change. It indeed feels artificial to require `:access_token` when we don't use it. A PR would be welcome if you can work on it sooner rather than later (I'm trying to get a release out :P), otherwise I can take care of this :).

**Comment by tt** [comment]
Thank you, @whatyouhide.
