### ISSUE TITLE
Sending exceptions as exceptions, not messages

### ISSUE THREAD

**Issue by Hermanverschooten** [elixir-addicts/rollbax#67]
Hi,
I was talking with someone from Rollbar yesterday, and we talked about the annoyance of having multiple items in Rollbar for the same errors (#56), he came back to me today and told me you are sending the exceptions as messages and not as exceptions.

**Comment by lexmag** [comment]
Hi @Hermanverschooten,
I assume you referring to exceptions that come from `Logger` calls, since `Rollbax.report/3` sends exceptions as exceptions. Currently we're reworking logging support, please see #62.

**Comment by Hermanverschooten** [comment]
Yes, I am.  I was talking about this on the slack channel this morning with @ericmj, and he suggested using :error_logger instead of Logger, as this would allow access to the exception, and not the already  formatted message. He said, I quote "basically you have mismatch by using logger. rollback reports errors, not logged messages". And I think this is true.

**Comment by lexmag** [comment]
Yes, in #62 we're moving to use `:error_logger`, and only send actual OTP crash reports, not regular Logger messages anymore.

**Comment by Hermanverschooten** [comment]
Great!  I'll keep an  👁 on it.
