### ISSUE TITLE
Expand config to allow setting defaults for the JSON msg

### ISSUE THREAD

**Issue by Hermanverschooten** [elixir-addicts/rollbax#68]
Due to the deployment of my app on different customer servers, I need to be able to track where the logged error originated.  Looking through the API documentation of Rollbar, I see they added the possibility to specify `user_ip : "$remote_ip"`, this will then be replaced with the reporting IP. I would love to be able to add in the config an option to set this all the time.
I know I can add a 5th parameter to `Rollbax.report` and this will be merged into the json, but I'd love it if we would be able to provide this from the config too.

**Comment by whatyouhide** [comment]
Custom data should be now possible to configure through `config :rollbax, :custom, ...`. If what you want is `:occurrence_data` that is customizable at a global level, let me know :) I'll close this issue for now then.
