### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by brightbits** [elixir-addicts/rollbax#8]
Hi there,

It doesn't specify but from looking at usage, does this only store things in Rollbar that are explicitly caught and sent to Rollbar, or will it catch unhandled exceptions?

**Comment by lexmag** [comment]
Hi @brightbits, there are two primary ways which covered in the README:
* explicit manual call for `Rollbax.report`
* use [notifier for the Logger](https://github.com/elixir-addicts/rollbax#notifier-for-logger)
in this case all error reports that have been logged will be sent to the Rollbar as well.
It covers almost everything in the system.

**Comment by brightbits** [comment]
Ahh, I see. I didn't clock on that `Logger` was the primary output method of exceptions that are raised. Thanks
