### ISSUE TITLE
Capturing error's background information

### ISSUE THREAD

**Issue by lessless** [elixir-addicts/rollbax#88]
Hi folks,

Do you think whether it's possible to capture more information that will ease an investigation, like:
- HTTP request 
- SQL query (if it happened within the Ecto, for example)

**Comment by whatyouhide** [comment]
Hey @lessless, Rollbax is not tied to Phoenix/Ecto in any particular way, so we're not likely to add anything like this. Plus, I am not sure that things like information about the HTTP request (= the `conn` struct) would be accessible to Rollbax in any way other than if the user would pass them explicitly).

We provide some guiding on how to integrate with Plug applications (hence Phoenix as well) [here](https://hexdocs.pm/rollbax/0.9.0-rc.1/using-rollbax-in-plug-based-applications.html).
