### ISSUE TITLE
Add a reporter for ranch/cowboy/Plug messages

### ISSUE THREAD

**Issue by whatyouhide** [elixir-addicts/rollbax#93]
Today we don't handle logs such as

```
Ranch listener ~p had connection process started with ~p:start_link/4 at ~p exit with reason: ~999999p~n
```

I think we should out of the box since they're incredibly common coming from cowboy/Plug. We can provide `Rollbax.Reporter.{Ranch|Cowboy|Plug}`. Thoughts @lexmag and @ericmj?

**Comment by ericmj** [comment]
What would it catch that https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html doesn't catch? Or would it be a way of automating the plug setup?

**Comment by whatyouhide** [comment]
@ericmj mh now that I think about it, I think it wouldn't catch anything that doing what is shown in that page wouldn't catch. Yes, this would get it automatically but the reporting would be less precise I think. @lexmag thoughts?

**Comment by whatyouhide** [comment]
I am fine with having this being reported as described in https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html so I'll close this. Feel free to reopen if you're not happy with the decision.
