### ISSUE TITLE
Problem with new guard in Rollbax.Item.draft/3

### ISSUE THREAD

**Issue by rafaels88** [elixir-addicts/rollbax#95]
After this implementation: https://github.com/elixir-addicts/rollbax/commit/47d89bd8765aa5872beed7d83cf05ea1b267651f#diff-17292547d1a8307b8d6fc61ce6dbf363R10

it is not possible to use `Confex` with Rollbax since the parameters don't match with the new guard.

Error example:

```
** (Mix) Could not start application rollbax: Rollbax.start(:normal, []) returned an error: shutdown: failed to start child: Rollbax.Client
    ** (EXIT) an exception was raised:
        ** (FunctionClauseError) no function clause matching in Rollbax.Item.draft/3
            (rollbax) lib/rollbax/item.ex:9: Rollbax.Item.draft({:system, "ROLLBAR_ACCESS_TOKEN", ""}, {:system, "ROLLBAR_ENVIRONMENT", ""}, %{})
            (rollbax) lib/rollbax/client.ex:28: Rollbax.Client.start_link/1
            (stdlib) supervisor.erl:365: :supervisor.do_start_child/2
            (stdlib) supervisor.erl:348: :supervisor.start_children/3
```

**Comment by rafaels88** [comment]
I could work on this if you folks feel it's ok and give me some thoughts on how to tackle it. :)

**Comment by whatyouhide** [comment]
We removed the possibility of passing `{:system, variable}` tuples in the configuration since we introduced `:config_callback` in #80. I think I just forgot to update the documentation which still mentions it can be used in some places. Could you maybe send a PR to fix the documentation? :)

**Comment by coderberry** [comment]
+1 on issue. I had to lock at v0.9.0 to make it work

**Comment by whatyouhide** [comment]
As I mentioned, this isn't a code issue, it's rather a documentation issue. I forgot to add that `{:system, var}` is not supported anymore to the documentation and to the changelog. I just pushed updates to the docs and the changelog. We're not going to support `{:system, var}` anymore, and it stopped working in 0.9 so this should not be a breaking change. Please update to `0.9.1` and use `:config_callback` to fetch stuff from the environment.
